platform :ios, '9.0'

target 'EarlGreyExample' do
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'SDWebImage'
  pod 'SwiftLint'

  target 'EarlGreyExampleTests' do
    inherit! :search_paths
    pod 'EarlGrey'
  end

  target 'EarlGreyExampleUITests' do
    inherit! :search_paths
  end

end
